# PyTorch

- Soporte de GPU: Ofrece soporte completo para la aceleración por GPU.
- Computación de tensores: PyTorch permite realizar operaciones sobre tensores, en muchas ocasiones de manera similizar a como se trabaja con Numpy.
- Autograd para la diferenciación automática: El módlulo `autograd` es una característica central de PyTorch, facilitando la diferenciación automática para el entrenamiento de redes neuronales.
- Ecosistema amplio: Existen librerías que trabajan sobre PyTorch como PyTorch Lightnining o HuggingFace Transformers.
- Implementación de modelos del estado del arte: PyTorch se utiliza para el entrenamiento y desarrollo de modelos del estado del arte.
- Felixibilidad para la investigación: Es ampliamente utilizado en el ámbito de la investigación para experimentar con arquitecturas de modelos complejas.

In [1]:
import torch

## Configuración inicial

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device seleccionado: {device}")

Device seleccionado: cpu


## Creación de tensores

In [3]:
# Crear un tensor de ceros
zeros = torch.zeros((3, 3))
print(f"Tensor de ceros:\n{zeros}")

Tensor de ceros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# Crear un tensor de unos
ones = torch.ones((2, 2))
print(f"Tensor de unos:\n{ones}")

Tensor de unos:
tensor([[1., 1.],
        [1., 1.]])


In [5]:
# Crear un tensor con valores aleatorios
random_tensor = torch.rand((3, 3))
print(f"Tensor con valores aleatorios:\n{random_tensor}")

Tensor con valores aleatorios:
tensor([[0.5631, 0.8562, 0.2577],
        [0.7064, 0.0540, 0.9601],
        [0.5362, 0.8617, 0.8042]])


In [6]:
# Crear un tensor de una secuencia
seq_tensor = torch.arange(0, 10)
print(f"Tensor de una secuencia:\n{seq_tensor}")

Tensor de una secuencia:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
# Crear un tensor con un tipo de dato específico (int32)
dtype_tensor = torch.zeros((2, 2), dtype=torch.int32)
print(f"Tensor con tipo de dato int32:\n{dtype_tensor}")

Tensor con tipo de dato int32:
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)


In [8]:
import numpy as np

# Crear tensor desde numpy
numpy_array = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.from_numpy(numpy_array)
print(f"Tensor de PyTorch creado desde el array de NumPy:\n{torch_tensor}")

Tensor de PyTorch creado desde el array de NumPy:
tensor([1, 2, 3, 4, 5])


## Operaciones con Tensores

In [9]:
a = torch.tensor([2, 3, 4], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

print(f"Tensor a: {a}")
print(f"Tensor b: {b}")

Tensor a: tensor([2., 3., 4.])
Tensor b: tensor([4., 5., 6.])


In [10]:
# Suma
suma = torch.add(a, b)
print(f"Suma de tensores:\n{suma}")

Suma de tensores:
tensor([ 6.,  8., 10.])


In [11]:
# Resta
resta = a - b
print(f"Resta de tensores:\n{resta}")

Resta de tensores:
tensor([-2., -2., -2.])


In [12]:
# División elemento a elemento
div = a / b
print(f"\nDivisión elemento a elemento:\n{div}")


División elemento a elemento:
tensor([0.5000, 0.6000, 0.6667])


In [13]:
# Multiplicación de matrices (producto punto)
c = torch.tensor([[1, 2], [3, 4]])
d = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor c:\n{c}")
print(f"\nTensor d:\n{d}")

mult = torch.mm(c, d)

print(f"\nProducto punto:\n{mult}")

Tensor c:
tensor([[1, 2],
        [3, 4]])

Tensor d:
tensor([[5, 6],
        [7, 8]])

Producto punto:
tensor([[19, 22],
        [43, 50]])


In [14]:
# Multiplicación de matrices elemento a elemento
mult_elem_by_elem = c * d
print(f"Producto punto:\n{mult_elem_by_elem}")

Producto punto:
tensor([[ 5, 12],
        [21, 32]])


In [15]:
# Exponenciación elemento a elemento
exp_elem_by_elem = a ** 2
print(f"Exponenciación elemento a elemento:\n{exp_elem_by_elem}")

Exponenciación elemento a elemento:
tensor([ 4.,  9., 16.])


## Indexación, concatenación y forma (shape)

In [16]:
tensor = torch.arange(1, 10).reshape(3, 3)
print(f"Tensor para indexar:\n{tensor}")

Tensor para indexar:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [17]:
# Obtener la fila 1
fila = tensor[1]
print(f"Primer fila del tensor:\n{fila}")

Primer fila del tensor:
tensor([4, 5, 6])


In [18]:
# Obtener el elemento de la posición 1, 1
elemento = tensor[1, 1]
print(f"Elemento en la posición (1,1):\n{elemento}")

Elemento en la posición (1,1):
5


In [19]:
# Obtener la columna 1
columna = tensor[:, 1]
print(f"Elemento en la posición (1,1):\n{columna}")

Elemento en la posición (1,1):
tensor([2, 5, 8])


In [20]:
# Cambio de tamaño y forma a una fila y 9 columnas
reshape_tensor = tensor.view(1, 9)
print(f"Tensor reconfigurado:\n{reshape_tensor}")

Tensor reconfigurado:
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


## Módulo autograd

- Diferenciación automática: Proporciona una forma automática de calcular los gradientes de los tensores con respecto a las variables que afectan a su cálculo.
- Facilidad para el cálculo del backpropagation: Calcula la operación de backpropagation de manera eficiente, calculando los gradientes que se necesitan para actualizar los parámetros del modelo en el proceso de aprendizaje.
- Optimización de parámetros: Los gradientes calculados por `autograd` son utilizados por algoritmos de optimización, como el descenso de gradiente, para ajustar los parámetros del modelo en el proceso de aprendizaje.

In [21]:
# Crear un tensor y establecer requires_grad=True para calcular automáticamente gradientes
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(f"Tensor original: {x}")

Tensor original: tensor([1., 2., 3.], requires_grad=True)


In [ ]:
# x = x * 2
# z = y * y * 3
# out igual a la media de z
y = x * 2
z = y * y * 3
out = z.mean()
print(f"Resultado de y: {y}")
print(f"\nResultado de x: {x}")
print(f"\nResultado de la operación: {out}")

Resultado de y: tensor([2., 4., 6.], grad_fn=<MulBackward0>)

Resultado de x: tensor([1., 2., 3.], requires_grad=True)

Resultado de la operación: 56.0


In [23]:
# Calcular los gradientes. TIP: Mirar función backward
out.backward()

# Mostrar el gradiente de x
x_grad = x.grad
print(f"Gradientes: {x_grad}")

Gradientes: tensor([ 8., 16., 24.])


## Implementación del algoritmo de backpropagation

In [24]:
x = torch.tensor([[1.], [2.], [3.], [4.]], requires_grad=False)
y = torch.tensor([[3.], [5.], [7.], [9.]], requires_grad=False)

print(f"Datos de entrada:\n{x}")
print(f"\nDatos de salida:\n{y}")

Datos de entrada:
tensor([[1.],
        [2.],
        [3.],
        [4.]])

Datos de salida:
tensor([[3.],
        [5.],
        [7.],
        [9.]])


In [25]:
# Crear un tensor w de 1 elemento aleatorio y con requires_grad=True
# Crear un tensor b de 1 elemento aleatorio y con requires_grad=True
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Pesos:\n{w}")
print(f"\nSesgos (bias):\n{b}")

Pesos:
tensor([1.7370], requires_grad=True)

Sesgos (bias):
tensor([-0.1732], requires_grad=True)


In [27]:
# Simular el entrenamiento de una red neuronal
learning_rate = 0.01
num_epochs = 1000

for epoch in range(num_epochs):
    # Forward pass: calcular la predicción
    y_pred = w * x + b

    # Calcular la pérdida (Mean Squared Error)
    loss = ((y_pred - y) ** 2).mean()

    # Backpropagation: calcular los gradientes
    loss.backward()

    # Actualizar los parámetros (w, b) usando descenso del gradiente
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # Poner a cero los gradientes después de la actualización. TIP: función zero_
    w.grad.zero_()
    b.grad.zero_()

    # Imprimir la pérdida cada 100 épocas
    if epoch % 100 == 0:
        print(f"Epoch {epoch + 1}:\tw = {w.item()},\tb = {b.item()},\tloss = {loss.item()}")

Epoch 1:	w = 2.0164260864257812,	b = 0.9517050385475159,	loss = 0.0003918825532309711
Epoch 101:	w = 2.0121707916259766,	b = 0.964216411113739,	loss = 0.00021513664978556335
Epoch 201:	w = 2.0090177059173584,	b = 0.9734867215156555,	loss = 0.00011810683645308018
Epoch 301:	w = 2.0066816806793213,	b = 0.980355441570282,	loss = 6.48383138468489e-05
Epoch 401:	w = 2.004950523376465,	b = 0.9854446053504944,	loss = 3.559567267075181e-05
Epoch 501:	w = 2.0036683082580566,	b = 0.9892147779464722,	loss = 1.9543593225535005e-05
Epoch 601:	w = 2.002718210220337,	b = 0.9920085668563843,	loss = 1.0729971108958125e-05
Epoch 701:	w = 2.002014398574829,	b = 0.9940780997276306,	loss = 5.8923660617438145e-06
Epoch 801:	w = 2.001492738723755,	b = 0.9956116080284119,	loss = 3.236283419028041e-06
Epoch 901:	w = 2.0011065006256104,	b = 0.9967479109764099,	loss = 1.7772972569218837e-06
